### ISSUE TITLE
`Cannot read property 'document' of undefined` error being thrown

### ISSUE THREAD

**Issue by kropptrevor** [mike-lischke/vscode-antlr4#104]
- Issue Type: `Bug`
- Extension Name: `vscode-antlr4`
- Extension Version: `2.2.3`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.42.0`

The error seems to be thrown everytime I switch tabs.

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 11742,
		"activateCallTime": 30,
		"activateResolvedTime": 13,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "mike-lischke.vscode-antlr4",
				"_lower": "mike-lischke.vscode-antlr4"
			},
			"activationEvent": "onLanguage:antlr"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```

**Comment by mike-lischke** [comment]
Any specific tabs between you switch or are these normal text/editor tabs?

**Comment by kropptrevor** [comment]
It isn't specific to a particular tab's contents (with respect to language), and it only happens when I switch to ANTLR at some point, because that starts it up.
I noticed that it only throws one uncaught error regardless of how many times I switch tabs before checking the _Running Extensions_ tabs. The number always updates after I switch to it. I thought it was just lag or something, but it seems like the error gets thrown on tabs like this.

**Comment by mike-lischke** [comment]
I tried to reproduce the issue, but couldn't. Have you already tried the latest version of the extension?

**Comment by kropptrevor** [comment]
I tried it on a new machine with the latest versions of everything, and it still occurs.
For whatever reason, nothing shows up in the Extension Host logs, but uncaught errors are still being thrown, which I see from the Running Extensions page.
I switch from empty document to the release notes 3 times, and then checked the Running Extensions, and the number of uncaught errors increased by 4 (1 for switching to Running Extensions).

Here is the stack trace from the developer console:
```
TypeError: Cannot read property 'document' of undefined
	at c:\Users\Trevor\.vscode\extensions\mike-lischke.vscode-antlr4-2.2.3\out\src\extension.js:168:36
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:770:777
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:663:482)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:804:1013)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:804:705)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:803:344)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:802:156)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:800:416
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:274)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:975:649
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:274)
	at t.PersistentProtocol._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:243:629)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:824
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:242)
	at p.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:737)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:89
	at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:245:185)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mike-lischke** [comment]
What type is the empty document? Is that a grammar file or something else?

If that is not a grammar file and you switch between that empty document and the release notes then I don't know how the antlr extension can even be involved here, as it is only invoked on ANTLR4 grammar files.

**Comment by kropptrevor** [comment]
I set the empty document language to ANTLR.

**Comment by mike-lischke** [comment]
I finally was able to reproduce the problem and fixed it.
