### ISSUE TITLE
Not generating the code

### ISSUE THREAD

**Issue by stefv** [mike-lischke/vscode-antlr4#21]
Hello,

I'm using the extension with 2 computers using Windows 10 Pro 64 bits. On my Surface pro, it's working fine generating the sources. But on my desktop computer, I have ANTRL in the status bar with the progress indicator but it doesn't generate the sources.

In the output console, I have this error:
[2018-02-17 08:58:19.214] [renderer1] [error] spawn java ENOENT : Error: spawn java ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)

I'm using Java 8 on both computer.

Regards,
Stef

**Comment by mike-lischke** [comment]
Very likely the Java compiler is not found. Can you open a terminal and run `java`? Make sure Java can be executed from any folder without giving it a path to actual binary.

**Comment by stefv** [comment]
Thank you very much: I added the path in my PATH and it's working now.
