### ISSUE TITLE
Debugging gets stuck with visualParseTree set to true

### ISSUE THREAD

**Issue by Shodan79** [mike-lischke/vscode-antlr4#37]
Hi,

up front let me say thank you very much for this fantastic extension!

I have configured the launch task according to documentation, and it prints correctly to the debug console, visual Parse Tree does not work though:
```
    "version": "2.0.0",
    "configurations": [        
        {
            "name": "antlr4-flow",
            "type": "antlr-debug",
            "request": "launch",
            //"input": "${workspaceFolder}/${command:AskForTestInput}",
            "input": "test.flow",
            "grammar": "flow.g4",
            "startRule": "file",
            "printParseTree": true,
            "visualParseTree": true
        }
    ]
```

If I set "visualParseTree" to false the debugger will start, print results to debug console and exit.

If it is set to true the debugger will start, print results to the debug console and then apparently get stuck (the toolbar with pause, restart, stop buttons is displayed but no visual parse tree appears).

Best regards,
Robert.

**Comment by mike-lischke** [comment]
Can you attach your grammar here, so I can take a look what might be wrong?

**Comment by Shodan79** [comment]
This is the grammar file I am playing with:
https://drive.google.com/open?id=1cmxPnnGVKlV1LouLHjIIUgWn3zKbz5dz

I found this in "renderer1.log", perhaps it is helpful:

[2018-06-13 08:56:15.990] [renderer1] [info] no standard startup: panel is active
[2018-06-13 08:57:06.983] [renderer1] [error] [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character: Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:45:689
	at t.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:45:1003)
	at new t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:47:756)
	at t.e.with (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:46:715)
	at Object.getTextProviderUri (C:\Users\Robert\.vscode\extensions\mike-lischke.vscode-antlr4-2.0.3\out\src\frontend\TextContentProvider.js:85:20)
	at GrapsDebugger.debugger.on (C:\Users\Robert\.vscode\extensions\mike-lischke.vscode-antlr4-2.0.3\out\src\frontend\AntlrDebugAdapter.js:264:94)
	at emitNone (events.js:86:13)
	at GrapsDebugger.emit (events.js:188:7)
	at Immediate._ (C:\Users\Robert\.vscode\extensions\mike-lischke.vscode-antlr4-2.0.3\out\src\backend\GrapsDebugger.js:261:18)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by KarimLUCCIN** [comment]
I think I also have that issue. It was working fine in VS Code 1.23.1 but doesn't work on 1.24.1 (the same grammar)

**Comment by fdammacco** [comment]
Same issue here, VS Code version 1.24.1

**Comment by TheGenezis** [comment]
Any updates please? @mike-lischke

**Comment by KarimLUCCIN** [comment]
It works now, thanks for fixing it @mike-lischke ! :)
