### ISSUE TITLE
Debug broken in September VSCode Release (version 1.28)

### ISSUE THREAD

**Issue by johnholliday** [mike-lischke/vscode-antlr4#50]
After installing the September, 2018 release of VSCode (version 1.28), the antlr4 debugging fails to run with the following error message: "Debug adapter process has terminated unexpectedly (read error)".

**Comment by johnholliday** [comment]
More Info: The Extensions output pane displays the following whenever I try to run the debugger.

`module.js:545
    throw err;
    ^
Error: Cannot find module 'undefined'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at [eval]:1:41
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Object.<anonymous> ([eval]-wrapper:8:3)
    at Module._compile (module.js:642:30)`

**Comment by johnholliday** [comment]
After spending the day digging into the bowels of the debug adapter (extreme!), I decided to simply copy the grammar file and a test file to a new project => no error.  Backtracking, I then happened to edit (and save) the grammar file in the original project, which automatically regenerated the parser.  Then ran the debugger => no error.

I was going to suggest a more descriptive error message, however after reading through the code and running a few tests, it appears that the "Function.Module._resolveFilename" exception is thrown before any of the debug adapter code is called.  I'm not completely certain of this, though.  Hopefully you can track this down.
